const data = {
    products: [
      {
        _id: "1",
        name: "Painting",
        category: "painting",
        image: "/images/p1.jpg",
        price: 2999,
        countInStock: 10,
        brand: "paintart",
        rating: 4.5,
        numReviews: 10,
        description: "amazing painting",
      },
      {
        _id: "2",
        name: "Rose sketch",
        category: "sketch",
        image: "/images/p2.jpg",
        price: 1599,
        countInStock: 20,
        brand: "sketchss",
        rating: 4.0,
        numReviews: 10,
        description: "beautifull sketch",
      },
      {
        _id: "3",
        name: "Sunsketch",
        category: "sketch",
        image: "/images/p3.jpg",
        price: 3499,
        countInStock: 0,
        brand: "sketches",
        rating: 4.8,
        numReviews: 17,
        description: "amazing sketch",
      },
      {
        _id: "4",
        name: "Men face sketch",
        category: "sketch",
        image: "/images/p4.jpg",
        price: 2599,
        countInStock: 15,
        brand: "sketches",
        rating: 4.5,
        numReviews: 8,
        description: "amazing sketch",
      },
      {
        _id: "5",
        name: "Flower sketch",
        category: "sketch",
        image: "/images/p5.jpg",
        price: 1599,
        countInStock: 5,
        brand: "sketchss",
        rating: 3.5,
        numReviews: 12,
        description: "amazing sketch",
      },
      {
        _id: "6",
        name: "Old man sketch",
        category: "sketch",
        image: "/images/p6.jpg",
        price: 3299,
        countInStock: 12,
        brand: "sketchess",
        rating: 4.5,
        numReviews: 20,
        description: "amazing sketch",
      },
      {
        _id: "7",
        name: "Scenery sketch",
        category: "sketch",
        image: "/images/p7.jpg",
        price: 1999,
        countInStock: 10,
        brand: "sketchss",
        rating: 3.5,
        numReviews: 23,
        description: "awesome sketch",
      },
      {
        _id: "8",
        name: "Galaxy sketch",
        category: "sketch",
        image: "/images/p8.jpg",
        price: 2799,
        countInStock: 10,
        brand: "sketchess",
        rating: 4.5,
        numReviews: 18,
        description: "amazing sketch",
      },
    ],
  };
  export default data;
  